

== Scope of this subproject

This subproject is focused on code examples of using "_Spring JWT stack_" tools.
This means libraries like `spring-security-oauth2-client` and - in particular -
the `nimbus-jose-jwt`. The intention is to exercise, how to use them in standalone,
outside of Spring Boot facility in order to understand them better.

== Client credentials grant - access token caching and getting new one on expiration.

By this I want to demonstrate how `spring-security-oauth2-client` can be used to
manage access tokens. This management involve *caching* and *requesting new one*
when previous expires.

Note that with *client credentials grant*, process of requesting new access token
doesn't involve refresh tokens. This is for following reasons:

* In client credentials flow, the *client itself is the subject* (not a user).

* Tokens are issued to the client ID + secret, so if the access token expires, the client
  can just request a new access token *directly* using its credentials.

* The spec (RFC 6749 ยง4.4) explicitly says refresh tokens are *not issued*
  in the client credentials flow.

== Generating signed access token with `nimbus-jose-jwt` for the needs of auto-tests.

(todo)

== The "parse-only" something with `nimbus-jose-jwt` ... if at all.

(todo)

