

== The Amazing World of Gumball

The Gumball characters are not so controversial like South Park, most of them have
realistic first and last names and possibly - easily recognizable avatars.

* *Gumball Watterson* +
  gumball_watterson3 +
  gumball.watterson@example.com

* *Richard Watterson* +
  richard_watterson5 +
  richard.watterson@example.com

* *Nicole Watterson* +
  nicole_watterson4 +
  nicole.watterson@example.com

* *Alan Keane* +
  alan_keane7 +
  alan.keane@example.com

* *Gaylord Robinson* +
  gaylord_robinson8 +
  gaylord.robinson@example.com

* *Tobias Wilson* +
  tobias_wilson1 +
  tobias.wilson@example.com

* *Larry Needlemeyer* +
  larry_needlemeyer2 +
  larry.needlemeyer@example.com


== The Simpsons


== Famous Chess Players


== Famous Mathematicians and Physicists

* *Isaac Newton* +
  isaac_newton +
  isaac.newton@mock.org

* *Albert Einstein* +
  Alberto_Ein5 +
  albert.einstein@example.edu

* *Galileo Galilei* +
  galileo_galilei +
  galilei1001@example.com

* *Marie Curie* +
  maria_salomea_sc +
  marie.curie@example.com

* *Niels Bohr* +
  NielsBohr3 +
  bohrniels@mock.com


== Famous Programmers

* *Alistair Cockburn* +
  alistair_cockburn +
  alistair_cockburn@example.com



== Famous Composers in Classical Music




== Famous Painters

* *Vincent van Gogh* +
  Vincent_vGogh +
  vincent.gogh@example.com


== Famous Explorers






