
spring:
  web:
    resources:
      #
      # Disable default mappings mentioned in
      # https://docs.spring.io/spring-boot/reference/web/reactive.html#web.reactive.webflux.static-content
      # See also:
      #   o.s.b.a.web.reactive.WebFluxAutoConfiguration.WebFluxConfig.addResourceHandlers
      #   o.s.b.a.web.WebProperties.Resources
      #
      add-mappings: false
      #
      # Limiting the auto o.s.b.a.web.reactive.WebFluxAutoConfiguration.WelcomePageConfiguration
      # to error pages only.
      # I want to explicitly configure index.html pages myself (by RouterFunction)
      #
      static-locations: ["classpath:/view-errors/"]
  webflux:
    base-path: "/webcntx"

defendev:
  gateway:
    oidc:
      azure:
        client-id: "00000000-0000-0000-0000-000000000000"
        client-secret: "-~aaa~aaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaa_a"
        authorization-uri: "https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/authorize"
        token-uri: "https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/token"
        user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
        jwk-set-uri: "https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/discovery/v2.0/keys"
      spring:
        client-id: "hZ519F1t6V"
        client-secret: "Hj2acmv3a1f0P2h"
        authorization-uri: "http://localhost:8010/defendev-authz/oauth2/authorize"
        token-uri: "http://localhost:8010/defendev-authz/oauth2/token"
        user-info-uri: "http://localhost:8010/defendev-authz/userinfo"
        jwk-set-uri: "http://localhost:8010/defendev-authz/oauth2/jwks"
