
server:
  servlet:
    context-path: "/backweb"
  port: 8012
  #
  # Setting explicitly to the default value of 8KB. In production scenario with Entra Id the token
  # size may exceed this limit (e.g. when security groups are included) and would require adjustment.
  #
  max-http-request-header-size: 8KB

defendev:
  resource-server:
    oidc:
      azure:
        iss: "https://sts.windows.net/d9d3ff2d-d7ca-4821-bd09-ed953ac26c13/"
        jwks-uri: "https://login.microsoftonline.com/d9d3ff2d-d7ca-4821-bd09-ed953ac26c13/discovery/v2.0/keys"
      sprin6authz:
        iss: "http://localhost:8010/defendev-authz"
        jwks-uri: "http://localhost:8010/defendev-authz/oauth2/jwks"


